apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c98wxqayl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c98wxqayl-nodejs 
  name: c98wxqayl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: c98wxqayl-nodejs 
